SAGE-3/next

webstack/clients/electron/electron.js, webstack/clients/electron/package.json, webstack/clients/electron/src/menuBuilder.js, webstack/clients/electron/yarn.lock
=> Add help links in Electron menubar

webstack/apps/webapp/src/app/pages/board/layers/background/components/Lasso.tsx
Fixed bug with lasso not resetting last mouse position when starting new selection.
=> Added on lines 63 & 64 to reset the mouse positions of lasso

webstack/apps/webapp/src/app/pages/board/layers/background/BackgroundLayer.tsx, webstack/apps/webapp/src/app/pages/board/layers/ui/components/AppToolbar.tsx
Feels better when deselecting an app (since one click triggers a dragStart).
=> Deselect an app when dragging the board. 

webstack/apps/webapp/src/app/pages/board/layers/background/components/Background.tsx, webstack/apps/webapp/src/app/pages/board/layers/ui/components/Panels/Asset/Files.tsx
- Limit to 20 the number of assets that can be opened at once (drag/drop or enter) from asset manager.
=> Limit on number of files opened at once from asset manager

foresight/board.py, foresight/proxy.py, foresight/smartbits/smartbit.py, foresight/utils/sage_communication.py, foresight/utils/sage_websocket.py
Found some issues with the python batch updates.
Python Organize now uses the batch update API.
=> Some fixes for Python to get batch working

webstack/libs/frontend/src/lib/ui/components/general/MainButton.tsx, webstack/libs/frontend/src/lib/ui/components/index.ts, webstack/libs/frontend/src/lib/ui/components/modals/UserSearchModal.tsx
#588 
https://user-images.githubusercontent.com/19752298/236095040-d76d9857-c289-4cb8-a8f7-63e674a2f733.mov
=> [User Search] Can search for users

webstack/libs/frontend/src/lib/stores/presence.ts, webstack/libs/frontend/src/lib/ui/components/modals/CreateUserModal.tsx, webstack/libs/frontend/src/lib/ui/components/modals/UserSearchModal.tsx
- as discussed in meeting
- hide guests
- blank list when no search term
- only active users
=> Tweak user search

deployment/configurations/node/sage3-prod.hjson, webstack/apps/webapp/src/app/pages/board/Board.tsx, webstack/libs/frontend/src/lib/hooks/useAuth.tsx, webstack/libs/frontend/src/lib/ui/components/modals/EditUserModal.tsx, webstack/libs/sagebase/src/lib/modules/auth/SBAuth.ts, webstack/sage3-dev.hjson, webstack/sage3-prod.hjson
- Default session time to 8 days (set in sage3-xxx.hjson file) to handle weekly meetings
- When close to expiration, show a model to login again
- Only in the board page now
- Not sure if it can be abstracted so can be used in room list page
=> Handle session expiration

webstack/libs/applications/src/lib/apps/PDFViewer/PDFViewer.tsx, webstack/libs/applications/src/lib/apps/VideoViewer/VideoViewer.tsx
- Discover `requestVideoFrameCallback` API, huge!
- added screenshot function to video viewer
https://github.com/SAGE-3/next/assets/5595452/a4c9bd92-c562-4f67-a4d0-f7e392974b6c
=> Capture videoframe

webstack/apps/homebase/src/api/routers/custom/asset.ts, webstack/apps/webapp/src/app/pages/board/layers/background/components/Lasso.tsx, webstack/apps/webapp/src/app/pages/board/layers/background/components/UserPresenceUpdate.tsx, webstack/apps/webapp/src/app/pages/board/layers/ui/components/Alfred.tsx, webstack/apps/webapp/src/app/pages/board/layers/ui/components/BoardContextMenu.tsx, webstack/apps/webapp/src/app/pages/board/layers/ui/components/LassoToolbar.tsx, webstack/apps/webapp/src/app/pages/board/layers/ui/components/Panels/Applications/ApplicationsPanel.tsx, webstack/apps/webapp/src/app/pages/board/layers/ui/components/Panels/Asset/CreateApp.tsx, webstack/apps/webapp/src/app/pages/board/layers/ui/components/Panels/Panel.tsx, webstack/apps/webapp/src/app/pages/board/layers/ui/components/Panels/Plugins/PluginsPanels.tsx, webstack/libs/applications/src/lib/apps/ChartMaker/ChartMaker.tsx, webstack/libs/applications/src/lib/apps/HCDP/HCDP.tsx, webstack/libs/applications/src/lib/apps/KernelDashboard/KernelDashboard.tsx, webstack/libs/applications/src/lib/apps/Kernels/Kernels.tsx, webstack/libs/applications/src/lib/apps/PDFResult/PDFResult.tsx, webstack/libs/applications/src/lib/apps/PDFViewer/PDFViewer.tsx, webstack/libs/applications/src/lib/apps/SageCell/components/outputs.tsx, webstack/libs/applications/src/lib/apps/Stickie/Stickie.tsx, webstack/libs/applications/src/lib/apps/VegaLite/VegaLite.tsx, webstack/libs/applications/src/lib/apps/Webview/Webview.tsx, webstack/libs/applications/src/lib/components/AppWindow.tsx, webstack/libs/applications/src/lib/schema.ts, webstack/libs/frontend/src/lib/hooks/useCursorBoardPosition.tsx, webstack/libs/frontend/src/lib/hooks/useFiles.tsx, webstack/libs/frontend/src/lib/stores/app.ts, webstack/libs/frontend/src/lib/stores/ui.ts, webstack/libs/frontend/src/lib/ui/components/general/FunctionButtons.tsx, webstack/libs/frontend/src/lib/ui/components/paste-handler/paste-handler.tsx
- Slow-rate update when resizing and moving windows
- window grey-ed out in remote view when interacting
- Do not work for groups (I got stuck).
https://github.com/SAGE-3/next/assets/5595452/a222b5b1-4912-4d1f-b018-c0167ec034d9
=> [UI] Update during resize and move

webstack/apps/homebase/src/api/collections/assets.ts, webstack/apps/homebase/src/processors/processor-metadata.ts, webstack/apps/webapp/src/app/pages/board/layers/ui/components/Panels/Asset/types.ts, webstack/libs/applications/src/lib/apps/VideoViewer/VideoViewer.tsx, webstack/libs/frontend/src/lib/hooks/useFiles.tsx, webstack/libs/shared/src/lib/types/schemas/asset.ts, webstack/libs/shared/src/lib/utils/mime-utils.ts, webstack/libs/workers/src/lib/metadata.ts
- extra video metadata in asset
- support quicktime '.mov' and hope
- spacebar to play
- info panel
- center the toolbar
- smaller screenshot
=> Video improvements

webstack/libs/applications/src/lib/components/AppWindow/AppWindow.tsx, webstack/libs/applications/src/lib/components/AppWindow/components/BlockInteraction.tsx, webstack/libs/applications/src/lib/components/AppWindow/components/ProcessingBox.tsx, webstack/libs/applications/src/lib/components/AppWindow/components/WindowBorder.tsx, webstack/libs/applications/src/lib/components/AppWindow/components/WindowTitle.tsx, webstack/libs/applications/src/lib/components/AppWindow/components/index.ts, webstack/libs/applications/src/lib/components/index.ts
=> [AppWindow] App Jittery movement fix

webstack/libs/applications/src/lib/apps/TwilioScreenshare/TwilioScreenshare.tsx
=> [UI] if board is locked, the screensharing app doesn't zoom to view.

webstack/libs/applications/src/lib/components/AppWindow/AppWindow.tsx, webstack/libs/frontend/src/lib/ui/components/paste-handler/paste-handler.tsx, webstack/libs/frontend/src/lib/utils/strings.ts
- paste in the board when no app selected
- a few more url embedding schemes
=> [UI] Better handling of pasting

webstack/apps/webapp/src/app/pages/board/layers/background/components/Cursors.tsx, webstack/apps/webapp/src/app/pages/board/layers/background/components/Viewports.tsx, webstack/apps/webapp/src/app/pages/board/layers/ui/components/BoardContextMenu.tsx, webstack/libs/frontend/src/lib/stores/ui.ts
=> [UI] add a toggle to show/hide presence (cursors and viewports)

webstack/apps/webapp/src/app/pages/board/layers/background/components/Whiteboard/Line.tsx, webstack/apps/webapp/src/app/pages/board/layers/background/components/Whiteboard/Whiteboard.tsx, webstack/apps/webapp/src/app/pages/board/layers/ui/components/Panels/Annotations/AnnotationsPanel.tsx, webstack/libs/frontend/src/lib/stores/ui.ts, webstack/libs/frontend/src/lib/ui/components/general/ColorPicker.tsx
-  fix color annotation per user,
- add size and opacity in UI store,
- add size and opacity in YJS model,
- draw lines with size and opacity.
- #634 
https://github.com/SAGE-3/next/assets/5595452/53a26347-fc3a-4905-9579-2781cce134ed
=> [Pen] opacity and size

webstack/apps/webapp/src/app/pages/board/layers/background/components/Apps.tsx, webstack/libs/frontend/src/lib/ui/components/paste-handler/paste-handler.tsx
- cmd+a / ctrl+a to select all apps
- can copy image and text files from Finder and paste the content
- 'c' to copy an app , 'v' to paste and app
- using ctrl or cmd introduces edge cases, with the paste handler
- works across boards in a room
=> Dev copy paste

deployment/configurations/jupyter/conf/start.sh, deployment/docker-compose-amd64.yml, deployment/docker-compose-arm64.yml, deployment/docker-compose-backend.yml, deployment/docker-compose.yml
=> [jupyter] docker image with python 3.9 and enabling LSP

webstack/apps/homebase/src/api/collections/assets.ts, webstack/apps/homebase/src/api/routers/custom/asset.ts, webstack/apps/webapp/src/app/pages/board/layers/background/components/Background.tsx, webstack/clients/cli/GO, webstack/clients/pycli/upload.py, webstack/libs/frontend/src/lib/hooks/useFiles.tsx, webstack/libs/frontend/src/lib/ui/components/paste-handler/paste-handler.tsx, webstack/package.json, webstack/yarn.lock
- removing app creation in the server (after upload)
=> [Cleanup]  Client opens the assets after upload is done

webstack/apps/webapp/src/app/pages/board/layers/background/components/Apps.tsx, webstack/libs/applications/src/lib/apps/Chat/Chat.tsx, webstack/libs/frontend/src/lib/ui/components/cards/UserCard.tsx
- tweaking the 'z' function
- fix color of stickie when dragging text out of chat
- tweaks in chat scrolling
=> [UI] small bugs

webstack/apps/webapp/src/app/pages/board/layers/ui/components/Panels/Users/UserAvatarGroup.tsx, webstack/apps/webapp/src/app/pages/board/layers/ui/components/PresenceFollow.tsx
=> Follow Magic

webstack/libs/applications/src/lib/apps/MapGL/MapGL.tsx, webstack/libs/applications/src/lib/apps/MapGL/index.ts
Fixed geojson issue
added bearing and pitch to state
#660
=> [MapGL] Fixed geojson disappearing when changing base layers

deployment/configurations/node/sage3-prod.hjson, webstack/apps/homebase/src/api/routers/custom/config.ts, webstack/apps/homebase/src/api/routers/custom/nlp.ts, webstack/libs/applications/src/lib/apps/Chat/Chat.tsx, webstack/libs/shared/src/lib/types/server/serverconfig.ts, webstack/package.json, webstack/sage3-dev.hjson, webstack/sage3-prod.hjson, webstack/yarn.lock
- using openai API
- add config in server to store the API key
- use @O to talk to openai
=> [App] chat with openai

webstack/apps/webapp/src/app/pages/board/layers/background/components/Background.tsx, webstack/apps/webapp/src/app/pages/board/layers/ui/components/BoardContextMenu.tsx, webstack/libs/frontend/src/lib/ui/components/paste-handler/paste-handler.tsx, webstack/package.json, webstack/yarn.lock
- Shows an option to create a weblink or webview when pasting/dropping a URL
https://github.com/SAGE-3/next/assets/5595452/08cb8407-0c27-47a4-a1a0-8fb68c915492
=> [UI] weblink webview

webstack/apps/webapp/src/app/pages/board/layers/ui/components/Panels/Controller/Controller.tsx, webstack/libs/frontend/src/lib/hooks/useRouteNav.tsx
https://github.com/SAGE-3/next/assets/5595452/d2cbd619-993a-44d7-8412-fc053b9dafb8
=> [UI] switch the back button to 'previous page'

webstack/apps/webapp/src/app/pages/board/layers/background/components/Background.tsx, webstack/libs/frontend/src/lib/ui/components/paste-handler/paste-handler.tsx
=> [UI] update the wording to create a link/url

webstack/apps/webapp/src/app/pages/board/layers/background/components/Apps.tsx
- delete selected apps with CTRL-D
- so can do: CTRL-A CTRL-D to delete all ,
- or lasso a few apps and CTRL-D
- instead the one under the cursor.
=> [Shortcut] delete selected apps

webstack/apps/webapp/src/app/pages/board/Board.tsx, webstack/clients/electron/electron.js, webstack/libs/frontend/src/lib/utils/copyboardurl.ts
=> [UI] add a message to use the desktop app when loaded in a browser

webstack/libs/applications/src/lib/components/AppWindow/AppWindow.tsx
- Limit on window size:
- min : 200 x 100 , was already there
- max: 8k x 8k, big enough ? too big?
- might address this #698
=> [UI]: Upper limit on window size (8k x 8k)

webstack/apps/webapp/src/app/pages/board/layers/background/components/Apps.tsx, webstack/apps/webapp/src/app/pages/board/layers/ui/components/AppToolbar.tsx
=> [UI] define a minimal toolbar with delete button for unknow app

webstack/apps/webapp/src/app/pages/board/layers/background/components/Apps.tsx, webstack/apps/webapp/src/app/pages/board/layers/background/components/Background.tsx, webstack/apps/webapp/src/app/pages/board/layers/ui/components/Panels/Asset/RowFile.tsx, webstack/apps/webapp/src/app/pages/board/layers/ui/components/Panels/Controller/Controller.tsx, webstack/apps/webapp/src/app/pages/board/layers/ui/components/Panels/Panel.tsx, webstack/libs/applications/src/lib/apps/Chat/Chat.tsx, webstack/libs/applications/src/lib/apps/WebpageLink/WebpageLink.tsx, webstack/libs/applications/src/lib/apps/Webview/Webview.tsx, webstack/libs/applications/src/lib/components/AppWindow/AppWindow.tsx, webstack/libs/frontend/src/lib/stores/ui.ts, webstack/libs/frontend/src/lib/ui/components/cards/BoardCard.tsx, webstack/libs/frontend/src/lib/ui/components/context-menu/ContextMenuHandler.tsx, webstack/libs/frontend/src/lib/ui/components/context-menu/context-menu.tsx, webstack/libs/frontend/src/lib/ui/components/modals/CreateBoardModal.tsx, webstack/libs/frontend/src/lib/ui/components/modals/CreateRoomModal.tsx, webstack/libs/frontend/src/lib/ui/components/modals/CreateUserModal.tsx, webstack/libs/frontend/src/lib/ui/components/modals/EditBoardModal.tsx, webstack/libs/frontend/src/lib/ui/components/modals/EditRoomModal.tsx, webstack/libs/frontend/src/lib/ui/components/modals/EditUserModal.tsx, webstack/libs/frontend/src/lib/utils/copyboardurl.ts
- removing warnings on iOS
- fixing touch
- 2-finger zoom
- needs testing
- ...
=> [UI] Fixing touch

webstack/apps/webapp/src/app/pages/board/layers/ui/components/AppToolbar.tsx
- Small UI tweak needed for touch-screeen
- Button in app toolbar already zoom into the app
- Add a zoom-out function when pressed again
- Label updated to 'Zoom Back' since the screenshots
=> [UI] zoom in/out

webstack/libs/applications/src/lib/apps/Stickie/Stickie.tsx
=> [UI] show font size in stickie toolbar

webstack/apps/webapp/src/app/pages/board/layers/background/BackgroundLayer.tsx, webstack/apps/webapp/src/app/pages/board/layers/background/components/Lasso.tsx, webstack/apps/webapp/src/app/pages/board/layers/background/components/Presence/Cursors.tsx, webstack/apps/webapp/src/app/pages/board/layers/background/components/Presence/Viewports.tsx, webstack/apps/webapp/src/app/pages/board/layers/background/components/Whiteboard/Whiteboard.tsx
ZIndex Fixes
Z Ordering
1. Cursors
2. Viewports
3. Lasso
4. Whiteboard
5. Apps
Fixed issue related to annotation lines now showing when entering a board from a BoardLink card.
=> [Whiteboard] Zindex Fixes and Entering Board not have Annotation Lines

webstack/apps/webapp/src/app/pages/board/layers/background/components/Presence/Cursors.tsx
```
<BsCursorFill color={color} style={{ transform: "rotate(-90deg) scale(1.3)" }} />
<Tag variant="solid" borderRadius="md" color="white" position="relative" top='12px' left="1px">
{props.name}
</Tag>
```
=> [UI] updated cursor

webstack/apps/webapp/src/app/pages/board/layers/ui/components/Panels/Annotations/AnnotationsPanel.tsx, webstack/libs/frontend/src/lib/ui/components/modals/ConfirmModal.tsx
=> [UI] delete annotation modals

webstack/apps/webapp/src/app/pages/board/layers/background/components/Whiteboard/Line.tsx, webstack/apps/webapp/src/app/pages/board/layers/background/components/Whiteboard/Whiteboard.tsx
#733 
https://github.com/SAGE-3/next/assets/19752298/a4039fc0-8c4b-4333-89a6-0947264a76db
=> [Annotations] Erase individual lines

webstack/apps/webapp/src/app/pages/board/layers/background/components/Background.tsx, webstack/libs/frontend/src/lib/hooks/useFiles.tsx
- each upload can have multiple files
- #736
=> [UI] only one upload at a time

webstack/apps/webapp/src/app/pages/board/layers/background/components/Whiteboard/Line.tsx, webstack/apps/webapp/src/app/pages/board/layers/background/components/Whiteboard/Whiteboard.tsx, webstack/apps/webapp/src/app/pages/board/layers/ui/components/Panels/Annotations/AnnotationsPanel.tsx, webstack/libs/frontend/src/lib/stores/ui.ts
- Add eraser mode
- disable pen when entering/leaving a board
=> [UI] eraser mode

webstack/apps/webapp/src/app/pages/board/Board.tsx, webstack/apps/webapp/src/app/pages/board/layers/background/components/Whiteboard/Line.tsx, webstack/apps/webapp/src/app/pages/board/layers/background/components/Whiteboard/Whiteboard.tsx, webstack/apps/webapp/src/app/pages/board/layers/ui/components/BoardContextMenu.tsx, webstack/apps/webapp/src/app/pages/board/layers/ui/components/Panels/Annotations/AnnotationsPanel.tsx, webstack/libs/applications/src/lib/components/AppWindow/AppWindow.tsx, webstack/libs/applications/src/lib/components/AppWindow/components/WindowTitle.tsx, webstack/libs/frontend/src/lib/stores/ui.ts
https://github.com/SAGE-3/next/assets/5595452/ff6e3d86-4d86-4517-9b6d-d192410eeeb6
=> [UI] show title when selected

webstack/libs/applications/src/lib/apps/SageCell/components/toolbar.tsx
I was attempting to make it smarter by changing the select depending on your current selection, but event were being lost since onChange isn't triggered if you select the same value in the Select dropdown.
=> [SAGECell] Group Toolbar Select

webstack/libs/frontend/src/lib/stores/plugin.ts
=> [Plugin] fix

webstack/libs/applications/src/lib/apps/TwilioScreenshare/TwilioScreenshare.tsx, webstack/libs/frontend/src/lib/stores/twilio.ts
https://github.com/twilio/twilio-video.js/issues/1812
=> [Twilio Screenshare] More performance tests

webstack/apps/webapp/src/app/pages/admin/Admin.tsx, webstack/apps/webapp/src/app/pages/admin/adminStyle.css, webstack/libs/applications/src/lib/apps/CSVViewer/CSVViewer.tsx, webstack/libs/applications/src/lib/apps/CSVViewer/styling.css, webstack/package.json, webstack/yarn.lock
=> [App] update CVSViewer

webstack/libs/applications/src/lib/apps/TwilioScreenshare/TwilioScreenshare.tsx, webstack/libs/frontend/src/lib/stores/twilio.ts
=> Revert "[Twilio Screenshare] More performance tests"

webstack/apps/webapp/src/app/pages/board/layers/background/components/Background.tsx, webstack/clients/electron/package.json, webstack/clients/electron/yarn.lock, webstack/libs/applications/src/lib/apps/SageCell/SageCell.tsx
Only thing I can see is maybe the awareness is messing with it...but not sure.
=> [SAGECell] Sync Mismatch

webstack/libs/applications/src/lib/apps/PDFViewer/PDFViewer.tsx, webstack/libs/applications/src/lib/apps/SageCell/SageCell.tsx, webstack/libs/applications/src/lib/apps/Stickie/Stickie.tsx, webstack/libs/applications/src/lib/apps/VideoViewer/VideoViewer.tsx, webstack/libs/applications/src/lib/components/AppWindow/AppWindow.tsx, webstack/libs/applications/src/lib/components/AppWindow/components/WindowBorder.tsx, webstack/package.json, webstack/yarn.lock
- Tweak the size of resize handles to get a bit bigger.
- ESC key in stickie, sagecell, pdf, movie
=> [UI] add ESC key to some apps to  deselect

webstack/libs/applications/src/lib/apps.json, webstack/libs/applications/src/lib/apps.ts, webstack/libs/applications/src/lib/apps/SageCell/SageCell.tsx, webstack/libs/applications/src/lib/apps/SageCell/components/monacoOptions.ts, webstack/libs/applications/src/lib/apps/SageCell/components/store.ts, webstack/libs/applications/src/lib/apps/SageCell/components/toolbar.tsx, webstack/libs/applications/src/lib/initialValues.ts, webstack/libs/applications/src/lib/types.ts, webstack/libs/frontend/src/lib/ui/theme/theme.ts
https://github.com/SAGE-3/next/assets/5595452/ff856a69-8ac4-4c59-8645-325c0edb50ad
=> [UI] open cells in a drawer

webstack/apps/webapp/src/app/pages/board/Board.tsx, webstack/apps/webapp/src/app/pages/board/layers/ui/components/Panels/Controller/Controller.tsx, webstack/apps/webapp/src/app/pages/board/layers/ui/components/Panels/Panel.tsx
- long press prop in controller buttons
- used for back button
- Could use some styling!
- 👍  /  👎 
https://github.com/SAGE-3/next/assets/5595452/171ba3f9-3d5e-4a70-9cd9-b61d5fc21053
=> [UI] add long press option in the main controller 'back' button

webstack/libs/applications/src/lib/apps/Cobrowse/Cobrowse.tsx, webstack/libs/applications/src/lib/apps/LeafLet/LeafLet.tsx, webstack/libs/applications/src/lib/apps/MapGL/MapGL.tsx, webstack/libs/applications/src/lib/apps/Notepad/Notepad.tsx, webstack/libs/applications/src/lib/apps/SageCell/SageCell.tsx, webstack/libs/applications/src/lib/apps/SageCell/components/statusbar.tsx, webstack/libs/applications/src/lib/apps/SageCell/components/store.ts, webstack/libs/applications/src/lib/apps/SageCell/components/toolbar.tsx, webstack/libs/applications/src/lib/apps/SensorOverview/MapGL.tsx, webstack/libs/applications/src/lib/apps/SensorOverview/viewers/MapViewer.tsx, webstack/libs/applications/src/lib/apps/TwilioScreenshare/TwilioScreenshare.tsx, webstack/libs/applications/src/lib/apps/VegaLiteViewer/VegaLiteViewer.tsx, webstack/libs/applications/src/lib/apps/WebpageLink/WebpageLink.tsx, webstack/libs/applications/src/lib/apps/Webview/Webview.tsx, webstack/libs/frontend/src/lib/stores/app.ts, webstack/libs/frontend/src/lib/stores/asset.ts, webstack/libs/frontend/src/lib/stores/board.ts, webstack/libs/frontend/src/lib/stores/config.ts, webstack/libs/frontend/src/lib/stores/insight.ts, webstack/libs/frontend/src/lib/stores/kernel.ts, webstack/libs/frontend/src/lib/stores/message.ts, webstack/libs/frontend/src/lib/stores/panel.ts, webstack/libs/frontend/src/lib/stores/plugin.ts, webstack/libs/frontend/src/lib/stores/presence.ts, webstack/libs/frontend/src/lib/stores/room.ts, webstack/libs/frontend/src/lib/stores/twilio.ts, webstack/libs/frontend/src/lib/stores/ui.ts, webstack/libs/frontend/src/lib/stores/user.ts, webstack/package.json, webstack/yarn.lock
- update stores
- better typing
=> [Update] zustand 4.4

webstack/apps/webapp/src/app/pages/board/layers/ui/components/AppToolbar.tsx
=> new: modal to confirm app delete

webstack/apps/webapp/src/app/pages/board/layers/ui/components/LassoToolbar.tsx, webstack/libs/applications/src/lib/apps/SageCell/SageCell.tsx
- Modified the 'clear' function to be able to undo
=> [UI] add prefix sage to magic variables. Add header for help.

webstack/apps/webapp/src/app/pages/board/layers/ui/components/LassoToolbar.tsx, webstack/apps/webapp/src/app/pages/board/layers/ui/components/Panels/Kernels/KernelsPanel.tsx, webstack/libs/applications/src/lib/apps/SageCell/SageCell.tsx, webstack/libs/frontend/src/lib/stores/kernel.ts
- trigger and stop the fastapi checks when the kernelPanel mounts and dismounts
=> [Ui] kernels checks

webstack/libs/frontend/src/lib/hooks/index.ts, webstack/libs/frontend/src/lib/hooks/useNetworkState.ts, webstack/libs/frontend/src/lib/ui/components/general/Clock.tsx
=> [UI] network status

webstack/apps/webapp/src/app/pages/board/layers/background/components/Apps.tsx, webstack/apps/webapp/src/app/pages/board/layers/background/components/Background.tsx, webstack/apps/webapp/src/app/pages/board/layers/ui/components/Alfred.tsx, webstack/apps/webapp/src/app/pages/board/layers/ui/components/AppToolbar.tsx, webstack/apps/webapp/src/app/pages/board/layers/ui/components/BoardContextMenu.tsx, webstack/apps/webapp/src/app/pages/board/layers/ui/components/LassoToolbar.tsx, webstack/apps/webapp/src/app/pages/board/layers/ui/components/Panels/Applications/ApplicationsPanel.tsx, webstack/apps/webapp/src/app/pages/board/layers/ui/components/Panels/Asset/CreateApp.tsx, webstack/apps/webapp/src/app/pages/board/layers/ui/components/Panels/Kernels/KernelsPanel.tsx, webstack/apps/webapp/src/app/pages/board/layers/ui/components/Panels/Plugins/PluginsPanels.tsx, webstack/libs/applications/src/lib/apps/ChartMaker/ChartMaker.tsx, webstack/libs/applications/src/lib/apps/PDFResult/PDFResult.tsx, webstack/libs/applications/src/lib/apps/PDFViewer/PDFViewer.tsx, webstack/libs/applications/src/lib/apps/SageCell/SageCell.tsx, webstack/libs/applications/src/lib/apps/Seer/components/outputs.tsx, webstack/libs/applications/src/lib/apps/SensorOverview/SensorOverview.tsx, webstack/libs/applications/src/lib/apps/Stickie/Stickie.tsx, webstack/libs/applications/src/lib/apps/VegaLite/VegaLite.tsx, webstack/libs/applications/src/lib/apps/Webview/Webview.tsx, webstack/libs/applications/src/lib/components/AppWindow/AppWindow.tsx, webstack/libs/applications/src/lib/components/AppWindow/components/WindowBorder.tsx, webstack/libs/applications/src/lib/schema.ts, webstack/libs/frontend/src/lib/hooks/useFiles.tsx, webstack/libs/frontend/src/lib/stores/app.ts, webstack/libs/frontend/src/lib/ui/components/general/FunctionButtons.tsx, webstack/libs/frontend/src/lib/ui/components/paste-handler/paste-handler.tsx, webstack/libs/frontend/src/lib/ui/theme/theme.ts, webstack/libs/shared/src/lib/permissions/SAGEAbility.ts
- locks the position and size
- doesn't lock the app state
- added to lasso toolbar
=> [UI] add pin/unpin functionality on the board

webstack/libs/applications/src/lib/apps/SageCell/components/toolbar.tsx, webstack/libs/applications/src/lib/apps/Stickie/Stickie.tsx
- Save stickies as .md files in asset manager
- Try to size stickies at creation based on the text lines and width.
=> [UI] Save stickies as .md and guess size at creation

webstack/apps/webapp/src/app/pages/board/layers/ui/components/Panels/Asset/RowFile.tsx, webstack/libs/frontend/src/lib/config/urls.ts
=> [Asset] generate public URL from the asset manager

deployment/configurations/jupyter/conf/start.sh, deployment/docker-compose-amd64.yml, deployment/docker-compose-arm64.yml, deployment/docker-compose-backend.yml, webstack/apps/webapp/src/app/pages/board/layers/background/components/Background.tsx, webstack/libs/applications/src/lib/apps/SageCell/SageCell.tsx, webstack/libs/applications/src/lib/apps/SageCell/components/help.tsx, webstack/libs/applications/src/lib/apps/SageCell/components/statusbar.tsx, webstack/libs/frontend/src/lib/ui/theme/theme.ts, webstack/package.json
- tweak the scrollbar on cell output
- make cell width a user preference
- updated Jupyter with LSP in backend, but not accessible to cell yet
- added new packages in backend for images/video processing (imageio)
- better output box size
- tweaked help panel
- better image drag/drop out of cells
=> [SAGECell] UI improvement

webstack/libs/applications/src/lib/apps/PluginApp/PluginApp.tsx, webstack/libs/frontend/src/lib/hooks/usePluginListener.tsx, webstack/libs/sageplugin/package.json, webstack/libs/sageplugin/src/lib/sageplugin.ts
- new: add user name in plugin init call
- #792
=> [Plugin] fix plugin warning and improvements

webstack/libs/applications/src/lib/apps/SensorOverview/SensorOverview.tsx
small change. Removed button to duplicate chart for all variables.
=> remove button to generate all charts

webstack/apps/webapp/src/app/pages/board/layers/ui/components/LassoToolbar.tsx, webstack/libs/applications/src/lib/apps/SageCell/SageCell.tsx, webstack/libs/applications/src/lib/apps/SageCell/components/store.ts, webstack/libs/applications/src/lib/apps/SageCell/components/toolbar.tsx
- in toolbar
- in grouped toolbar
=> [UI] Add eval/interrupt buttons to sagecells

deployment/configurations/jupyter/conf/start.sh, foresight/foresight/Sage3Sugar/pysage3.py, foresight/foresight/smartbitfactory.py, foresight/foresight/smartbits/chat.py, foresight/foresight/smartbits/mapgl.py, foresight/foresight/smartbits/stickie.py, foresight/foresight/smartbits/webview.py, foresight/foresight/utils/sage_communication.py, webstack/libs/applications/src/lib/apps.json, webstack/libs/applications/src/lib/apps.ts, webstack/libs/applications/src/lib/apps/IFrame/IFrame.tsx, webstack/libs/applications/src/lib/apps/IFrame/index.ts, webstack/libs/applications/src/lib/apps/PluginApp/PluginApp.tsx, webstack/libs/applications/src/lib/apps/SageCell/SageCell.tsx, webstack/libs/applications/src/lib/apps/SageCell/components/store.ts, webstack/libs/applications/src/lib/apps/Stickie/Stickie.tsx, webstack/libs/applications/src/lib/initialValues.ts, webstack/libs/applications/src/lib/types.ts
- add IFrame  app to show HTML  content
- fix stickie copy state
- fix multiple menu entries in sagecell
- more smartbits
- upload_file function
- simplify data returned by all tags
=> [Cell] improvements

webstack/libs/applications/src/lib/apps/SensorOverview/SensorOverview.tsx, webstack/libs/applications/src/lib/apps/SensorOverview/viewers/EChartsViewer.tsx, webstack/libs/applications/src/lib/apps/SensorOverview/viewers/FriendlyVariableCard.tsx, webstack/libs/applications/src/lib/apps/SensorOverview/viewers/StatisticCard.tsx, webstack/libs/applications/src/lib/apps/SensorOverview/viewers/VariableCard.tsx
Updated the spinner to load charts to 1s instead of .30s.
=> reduced the speed of spinner

webstack/libs/applications/src/lib/apps/Stickie/Stickie.tsx
=> [Stickie] add scrollbar to stickies, and remove automatic guessing of size.

webstack/libs/applications/src/lib/apps/SensorOverview/SensorOverview.tsx, webstack/libs/applications/src/lib/apps/SensorOverview/viewers/EChartsViewer.tsx, webstack/libs/applications/src/lib/apps/SensorOverview/viewers/FriendlyVariableCard.tsx, webstack/libs/applications/src/lib/apps/SensorOverview/viewers/StatisticCard.tsx, webstack/libs/applications/src/lib/apps/SensorOverview/viewers/VariableCard.tsx
made the loader too big. Reduced to 5px
=> reduced size of spinner

webstack/libs/applications/src/lib/apps/SensorOverview/SensorOverview.tsx, webstack/libs/applications/src/lib/apps/SensorOverview/data/stationData.ts
=> Added a station

webstack/apps/webapp/src/app/pages/board/layers/background/components/Lasso.tsx, webstack/libs/applications/src/lib/apps/SensorOverview/viewers/FriendlyVariableCard.tsx, webstack/libs/applications/src/lib/apps/SensorOverview/viewers/VariableCard.tsx
https://github.com/SAGE-3/next/assets/35385849/985249a1-2731-40d3-84ac-76d693ac13e6
=> Add multi select

webstack/apps/webapp/src/app/pages/board/layers/background/BackgroundLayer.tsx, webstack/libs/applications/src/lib/apps/ImageViewer/ImageViewer.tsx, webstack/libs/applications/src/lib/components/AppWindow/AppWindow.tsx
- Added to imageviewer
- Doesn't use the WindowBorder component (div), but just css outline
=> [UI] add background prop to AppWindow to support window with alpha

webstack/libs/applications/src/lib/apps/SensorOverview/SensorOverview.tsx, webstack/libs/applications/src/lib/apps/SensorOverview/styling.css, webstack/libs/applications/src/lib/apps/SensorOverview/viewers/MapViewer.tsx, webstack/libs/applications/src/lib/apps/SensorOverview/viewers/StatisticCard.tsx
Small bug fixes and styling changes
=> Hcdp lightmode

webstack/libs/applications/src/lib/apps/TwilioScreenshare/TwilioScreenshare.tsx, webstack/sage3-dev.hjson
Different way of removing screenshares beyond the first one.
Was a bug where you could spam screenshares and get some stuck.
=> [Screenshare] Spamming screenshares can break the limiting mechanism

webstack/apps/homebase/src/api/collections/plugins.ts
- dealing with #834 
- put a few extra checks when uploading a plugin
=> fix: dealing with plugin upload

webstack/apps/webapp/src/app/pages/home/Home.tsx
Unjoin room button fix.
Double click on recent/saved boards joins them.
=> [Bug] Unjoin Button fix

webstack/apps/webapp/src/app/pages/board/layers/ui/components/AppToolbar.tsx
- add function to restore the size after 'present'
=> [UI] Dev restore present

webstack/apps/webapp/src/app/pages/board/layers/background/components/Whiteboard/Whiteboard.tsx, webstack/package.json, webstack/yarn.lock
=> [BUG] fix annotations

webstack/apps/webapp/src/app/pages/board/layers/ui/components/Panels/Applications/ApplicationsPanel.tsx, webstack/apps/webapp/src/app/pages/board/layers/ui/components/Panels/Panel.tsx, webstack/apps/webapp/src/app/pages/board/layers/ui/components/Panels/Plugins/PluginsPanels.tsx
converted to standard draggable.
=> [UI] fix props panel issue with canDrag,

webstack/apps/webapp/src/app/pages/board/Board.tsx, webstack/apps/webapp/src/app/pages/board/layers/background/BackgroundLayer.tsx, webstack/apps/webapp/src/app/pages/board/layers/background/components/Whiteboard/Whiteboard.tsx
move annotation subscription to WhiteBoard component.
=> [FIX] Dev duplicate annotations

webstack/apps/webapp/src/app/pages/board/layers/background/components/Background.tsx, webstack/apps/webapp/src/app/pages/board/layers/background/components/Whiteboard/Whiteboard.tsx, webstack/libs/applications/src/lib/apps/CodeEditor/CodeEditor.tsx, webstack/libs/applications/src/lib/apps/SageCell/SageCell.tsx, webstack/libs/applications/src/lib/apps/Stickie/Stickie.tsx, webstack/libs/frontend/src/lib/providers/useYjs.tsx, webstack/package.json, webstack/yarn.lock
Yjs connection init wrapped in promise
I don't render the board until yjs finishes connection
Throttle Stickie app creation
useYjs now provides simpler to use interface that proves `yApps` and `yAnnotations`. More could be added
=> [Yjs] Introduced Promise and conditional rendering

webstack/libs/applications/src/lib/apps/BoardLink/BoardLink.tsx, webstack/libs/applications/src/lib/apps/Chat/Chat.tsx, webstack/libs/applications/src/lib/apps/CodeEditor/CodeEditor.tsx, webstack/libs/applications/src/lib/apps/ImageViewer/ImageViewer.tsx, webstack/libs/applications/src/lib/apps/MapGL/MapGL.tsx, webstack/libs/applications/src/lib/apps/PDFViewer/PDFViewer.tsx, webstack/libs/applications/src/lib/apps/PluginApp/PluginApp.tsx, webstack/libs/applications/src/lib/apps/SageCell/SageCell.tsx, webstack/libs/applications/src/lib/apps/SensorOverview/SensorOverview.tsx, webstack/libs/applications/src/lib/apps/Stickie/Stickie.tsx, webstack/libs/applications/src/lib/apps/TwilioScreenshare/TwilioScreenshare.tsx, webstack/libs/applications/src/lib/apps/VideoViewer/VideoViewer.tsx, webstack/libs/applications/src/lib/apps/WebpageLink/WebpageLink.tsx, webstack/libs/applications/src/lib/apps/Webview/Webview.tsx, webstack/libs/applications/src/lib/components/AppWindow/AppWindow.tsx
https://github.com/SAGE-3/next/assets/19752298/6a8bb81d-10d6-4e85-afc7-3c3d3d71604c
=> [Performance UI] Made apps uniform when not rendering them when panning

webstack/clients/electron/package.json, webstack/clients/electron/yarn.lock
Chromium 124.0.6367.49
[New in 124](https://developer.chrome.com/blog/new-in-chrome-124/)
[New in 123](https://developer.chrome.com/blog/new-in-chrome-123/)
Node 20.11.1
[Node 20.11.1 blog post](https://nodejs.org/en/blog/release/v20.11.1/)
=> [Client] update to electron 30

webstack/apps/webapp/src/app/pages/home/Home.tsx
Added a search input box on the board list within a room. Clears input when switching rooms
https://github.com/SAGE-3/next/assets/19752298/4691facc-ec7c-4015-b5cc-2100f8c1bf3d
=> [Home Page] Board Search

webstack/libs/applications/src/lib/apps/Notepad/Notepad.tsx
Removed ability to paste images due to large images breaking reds
fixed database sync
=> [Notepad] Testing time

webstack/libs/applications/src/lib/apps/Stickie/Stickie.tsx
Changed OnChange to OnInput for stickies so we trigger the event when user's paste into the stickie.
=> [Stickies] OnInput

webstack/apps/webapp/src/app/pages/home/Home.tsx, webstack/libs/shared/src/lib/utils/fuzzy-search.ts, webstack/libs/shared/src/lib/utils/index.ts
Modifications:
- Changed board filter to a imitation fuzzy search with regex to allow for loose matches.
- Clear search bar when selecting a board from the side navigation menu.
- Added scroll to into view for user selected board via ref.
=> Improvements to Searching

webstack/apps/webapp/src/app/pages/home/Home.tsx, webstack/apps/webapp/src/app/pages/home/components/BoardSidebarRow.tsx, webstack/apps/webapp/src/app/pages/home/components/index.ts
- Added **Active Boards** accordion sorted by alpha with priority on user count.
- Will only show Boards from Rooms the user is subscribed to.
- Added lock icon and grey inactivity to **BoardSideRow**.
- **BoardSideRow** is a new file created where the sidebar board row component now resides in.
- Modified spacing and added divider for Boards and Rooms on the sidebar.
- Gray color for visual hierarchy for top header **Created by...** and **Created on...**.
- Modified **Recent Boards** accordion to sort by user's last visited.
=> Homepage Sidebar New Features and Improvements

deployment/configurations/jupyter/conf/start.sh, deployment/docker-compose-amd64.yml, deployment/docker-compose-arm64.yml, deployment/docker-compose-backend.yml, webstack/libs/applications/src/lib/apps.json, webstack/libs/applications/src/lib/apps.ts, webstack/libs/applications/src/lib/apps/JupyterLab/JupyterLab.tsx, webstack/libs/applications/src/lib/apps/JupyterLab/index.ts, webstack/libs/applications/src/lib/initialValues.ts, webstack/libs/applications/src/lib/types.ts, webstack/libs/frontend/src/lib/hooks/useFiles.tsx, webstack/libs/frontend/src/lib/utils/setupAppForFiles.ts, webstack/libs/shared/src/lib/utils/mime-utils.ts
- enabling traditional single view of notebook
- see if it works...
- missing sync between evaluation for now
=> Dev traditional notebook

webstack/apps/webapp/src/assets/version.json, webstack/clients/electron/package.json, webstack/clients/electron/yarn.lock, webstack/libs/frontend/src/lib/hooks/index.ts, webstack/libs/frontend/src/lib/hooks/usePressureObserver.ts, webstack/libs/frontend/src/lib/ui/components/general/Clock.tsx
- need electron v31, for Chrome 125
- https://developer.chrome.com/docs/web-platform/compute-pressure
=> [UI] Add pressure observer

webstack/clients/electron/electron.js, webstack/clients/electron/src/menuBuilder.js
- add 'About' menu item in 'help' (since Windows doesn't have one)
- check update every 10mins
- popup when no update
- Issue #967
=> Dev check update

webstack/libs/applications/src/lib/apps/TLDraw/TLDraw.tsx, webstack/package.json, webstack/yarn.lock
- update package
- show/hide UI when app selected
- add 100% zoom button
=> [APP] tldraw update

webstack/libs/applications/src/lib/apps/Chat/Chat.tsx, webstack/libs/applications/src/lib/apps/Chat/index.ts
https://github.com/user-attachments/assets/67587587-8b17-42cf-88ee-7ce7d3b15fb7
=> [CHAT] no more Geppetto and an automatic AI question detection

webstack/clients/electron/css/landing.css, webstack/clients/electron/html/landing.html, webstack/clients/electron/src/menuBuilder.js, webstack/libs/frontend/src/lib/ui/components/modals/EnterBoardByURLModal.tsx
=> [UI] Join a Board from the landing page

deployment/configurations/node/sage3-prod.hjson, webstack/apps/homebase/src/api/routers/custom/config.ts, webstack/libs/frontend/src/lib/ui/components/general/MainButton.tsx, webstack/libs/frontend/src/lib/ui/components/modals/FeedbackModal.tsx, webstack/libs/frontend/src/lib/ui/components/modals/index.ts, webstack/libs/shared/src/lib/types/server/serverconfig.ts, webstack/sage3-dev.hjson, webstack/sage3-prod.hjson
https://github.com/user-attachments/assets/c86964b5-67f3-4d26-92bd-7dde128d942c
=> [Support] Feedback modal to submit bugs and feedback 

webstack/apps/webapp/src/app/pages/board/layers/ui/components/Panels/Navigation/NavigationPanel.tsx, webstack/package.json, webstack/yarn.lock
-  colors based on app, or stickie color
- better on large displays with touch
=> [UI] improving minimap

webstack/apps/webapp/src/app/pages/board/layers/ui/UILayer.tsx, webstack/libs/frontend/src/lib/ui/components/general/Clock.tsx, webstack/libs/frontend/src/lib/ui/components/general/MainButton.tsx
=> [UI] controls into the main menu

webstack/apps/webapp/src/app/pages/board/layers/ui/UILayer.tsx, webstack/apps/webapp/src/app/pages/board/layers/ui/components/AppToolbar.tsx, webstack/apps/webapp/src/app/pages/board/layers/ui/components/Panels/Navigation/NavigationPanel.tsx, webstack/apps/webapp/src/app/pages/board/layers/ui/components/TagsDisplay.tsx, webstack/libs/applications/src/lib/apps/Stickie/Stickie.tsx, webstack/libs/frontend/src/lib/providers/useUserSettings.tsx, webstack/libs/frontend/src/lib/ui/components/modals/EditVisibilityModal.tsx
=> [Tags] Fix issues with the tag system

webstack/apps/webapp/src/app/pages/home/components/BoardCard.tsx, webstack/libs/applications/src/lib/apps/PDFViewer/PDFViewer.tsx
- Left side goes back,
- right side goes forward.
- Should work with touch on Windows (didn't try yet).
Addresses issue #874 
https://github.com/user-attachments/assets/86542159-bbfb-4777-9fc0-9fd024634d6b
=> [UI] add double click/touch to navigate PDF

deployment/configurations/node/sage3-prod.hjson, webstack/apps/homebase/src/api/routers/custom/ai/ai-router.ts, webstack/apps/homebase/src/api/routers/custom/ai/models/code-llama/code-llama.ts, webstack/apps/homebase/src/api/routers/custom/ai/models/open-ai/open-ai.ts, webstack/apps/webapp/src/app/pages/board/layers/background/components/Background.tsx, webstack/apps/webapp/src/app/pages/board/layers/ui/components/BoardContextMenu.tsx, webstack/apps/webapp/src/app/pages/board/layers/ui/components/Panels/Applications/ApplicationsPanel.tsx, webstack/libs/applications/src/lib/apps/Chat/index.ts, webstack/libs/applications/src/lib/apps/CodeEditor/CodeEditor.tsx, webstack/libs/applications/src/lib/apps/CodeEditor/ai-request-generator.ts, webstack/libs/shared/src/lib/ai/ai-api.ts, webstack/libs/shared/src/lib/types/server/serverconfig.ts, webstack/sage3-dev.hjson, webstack/sage3-prod.hjson
- explain, refactor, generate, comment
- using Llama3.1 with Nvidia NIM, using OpenAI message API
- 7B model with long context, fast
=> [AI] restore code AI in codeEditor

webstack/apps/homebase/src/api/collections/roommembers.ts, webstack/apps/webapp/src/app/pages/board/Board.tsx, webstack/apps/webapp/src/app/pages/board/layers/ui/components/Panels/Annotations/AnnotationsPanel.tsx, webstack/apps/webapp/src/app/pages/board/layers/ui/components/Panels/Controller/Controller.tsx, webstack/apps/webapp/src/app/pages/board/layers/ui/components/Panels/Panel.tsx, webstack/apps/webapp/src/app/pages/home/Home.tsx, webstack/apps/webapp/src/app/pages/home/components/BoardCard.tsx, webstack/apps/webapp/src/app/pages/home/components/BoardRow.tsx, webstack/apps/webapp/src/app/pages/home/components/UserRow.tsx, webstack/libs/frontend/src/lib/stores/panel.ts, webstack/libs/frontend/src/lib/stores/room.ts
#1009 
https://github.com/user-attachments/assets/6d47963a-77ee-4b21-ba9e-7aa7c35b1008
=> [Rooms] Remove a member from a room

webstack/apps/webapp/src/app/app.tsx, webstack/apps/webapp/src/app/pages/client/Client.tsx, webstack/apps/webapp/src/app/pages/home/components/BoardCard.tsx, webstack/apps/webapp/src/app/pages/home/components/BoardRow.tsx, webstack/apps/webapp/src/app/pages/index.ts, webstack/libs/frontend/src/lib/ui/components/general/MainButton.tsx, webstack/libs/frontend/src/lib/ui/components/modals/EnterBoardByURLModal.tsx, webstack/libs/frontend/src/lib/ui/components/paste-handler/paste-handler.tsx, webstack/libs/frontend/src/lib/utils/copyboardurl.ts
=> new: add a page to catch sage3 enter url and open the desktop client

webstack/apps/webapp/src/app/pages/board/layers/background/components/Background.tsx, webstack/apps/webapp/src/app/pages/board/layers/ui/UILayer.tsx, webstack/apps/webapp/src/app/pages/board/layers/ui/components/Panels/Panel.tsx
Fixes proposed that address the following issues:
https://github.com/SAGE-3/next/issues/1034
- Interaction mode doesn't return to the original when drag and drop
https://github.com/SAGE-3/next/issues/1036
- In grab mode, trying to move panels move the board too
=> [Controls] New Interaction Scheme Fixes

webstack/apps/webapp/src/app/pages/home/Home.tsx
=> [UI][Bug] Bug fixes

webstack/apps/webapp/src/app/pages/board/Board.tsx, webstack/apps/webapp/src/app/pages/board/layers/background/BackgroundLayer.tsx, webstack/apps/webapp/src/app/pages/board/layers/background/components/Background.tsx, webstack/apps/webapp/src/app/pages/board/layers/background/components/DragAndDropBoard.tsx, webstack/apps/webapp/src/app/pages/board/layers/background/components/Lasso.tsx, webstack/apps/webapp/src/app/pages/board/layers/background/components/Whiteboard/Whiteboard.tsx, webstack/apps/webapp/src/app/pages/board/layers/background/components/index.ts, webstack/apps/webapp/src/app/pages/board/layers/ui/UILayer.tsx, webstack/apps/webapp/src/app/pages/board/layers/ui/components/Interactionbar.tsx, webstack/apps/webapp/src/app/pages/board/layers/ui/components/Panels/Panel.tsx, webstack/apps/webapp/src/app/pages/board/layers/ui/components/index.ts, webstack/libs/frontend/src/lib/stores/ui.ts, webstack/libs/frontend/src/lib/ui/components/context-menu/context-menu.tsx
- https://github.com/SAGE-3/next/issues/1042
- Removed prior hacky way (switching the input modes on drag) to get drag and drop to work since there was repeated issues with the current implementation
- Added custom hook with render function solution instead such that each of the ['board', 'whiteboard', 'lasso'] HTML elements calls this functionality. 
- Not extensively tested, but seems to work with limited testing
- Added Pen and Eraser Input to interaction bar (bottom left)
- ![image](https://github.com/user-attachments/assets/50f0030d-89a9-4523-8312-005f762edadd)
- Removed whiteboard, setWhiteboard and moved those states to primaryActionMode.
| Interaction | Applications -> Board | Chat Message -> Board | (One PNG Image File) External Files -> Board | SageCell -> Board |
| --- | --- | …
=> [Controls] Fixes and Improvements

webstack/apps/webapp/src/app/pages/board/layers/background/components/DragAndDropBoard.tsx
=> [Bug] Fix bug where users can't drop apps into board even though they are logged in

webstack/apps/webapp/src/app/pages/board/layers/background/components/DragAndDropBoard.tsx
Added canDrop to dependency list of OnDrop handler in DragAndDropBoard.tsx.
=> [Bug] Fix drag and drop bug

webstack/libs/frontend/src/lib/hooks/useFiles.tsx
- rename the image coming from 'Copy Image'
- Use the username and the date
=> [UI] rename 'screenshot' before upload 

webstack/apps/webapp/src/app/pages/board/layers/background/components/Whiteboard/Line.tsx, webstack/apps/webapp/src/app/pages/board/layers/background/components/Whiteboard/Whiteboard.tsx
=> [Annotation] Erase single line with eraser fix

webstack/libs/applications/src/lib/apps/Timer/Timer.tsx, webstack/libs/applications/src/lib/apps/Timer/index.ts
=> [Timer] Fix desync issues

webstack/apps/webapp/src/app/app.tsx, webstack/libs/frontend/src/lib/ui/components/general/MainButton.tsx
- Fix for admin route only loading for Google Users
- Admin page button in the main button is now enabled if in development mode for all users
#1057
=> [Admin] Fix for admin route only working for google users

webstack/apps/webapp/src/app/app.tsx, webstack/libs/frontend/src/lib/providers/useYjs.tsx
A route check on the BoardRoute to check to see if aboard exists before entering.
Shows a toast if the board doesn't exist and navigates the user to the HomePage.
=> [Board] Spooky Ghost Board Fix 👻👻

webstack/apps/webapp/src/app/pages/board/layers/ui/UILayer.tsx, webstack/apps/webapp/src/app/pages/board/layers/ui/components/ScreenshareMenu.tsx, webstack/apps/webapp/src/app/pages/board/layers/ui/components/index.ts, webstack/libs/frontend/src/lib/ui/components/context-menu/context-menu.tsx, webstack/libs/frontend/src/lib/ui/components/general/MainButton.tsx
Menu on the UI Layer of screenshares. Shows a list of available Screenshares and allows the the user to start and stop their own screenshare
https://github.com/user-attachments/assets/d391bcfd-457c-4663-bf07-7581f6c15b17
=> [UILayer] Screenshare Menu 

webstack/libs/frontend/src/lib/hooks/useFiles.tsx
…oasts with some progress bars
=> [Drag Drop] Wrapped some functionality in UseCallbacks 

webstack/apps/webapp/src/app/pages/board/layers/ui/components/BoardTitle.tsx, webstack/apps/webapp/src/app/pages/board/layers/ui/components/Panels/Controller/Controller.tsx, webstack/apps/webapp/src/app/pages/board/layers/ui/components/Panels/Panel.tsx
https://github.com/user-attachments/assets/51163c98-2a1d-43d8-a8dc-e93a0e20bd02
=> [UI] Moved Board Back Button into board title

webstack/apps/webapp/src/app/pages/board/layers/ui/components/Interactionbar.tsx, webstack/apps/webapp/src/app/pages/board/layers/ui/components/Panels/Controller/Controller.tsx
https://github.com/user-attachments/assets/f8b057d8-ce8f-48e3-891e-60ff9ff28e41
=> [Annotation] UI in bottom left hand corner. Similar to other apps.

deployment/configurations/node/sage3-prod.hjson, deployment/docker-compose-amd64.yml, deployment/docker-compose-arm64.yml, webstack/apps/homebase/src/api/collections/assets.ts, webstack/apps/homebase/src/api/routers/custom/asset.ts, webstack/apps/homebase/src/config/configuration.ts, webstack/apps/homebase/src/connectors/upload-connector.ts, webstack/apps/homebase/src/main.ts, webstack/apps/homebase/src/web/http-server.ts, webstack/apps/webapp/src/app/pages/board/layers/ui/components/Panels/Asset/RowFile.tsx, webstack/apps/webapp/src/app/pages/home/components/AssetList.tsx, webstack/libs/applications/src/lib/apps/PDFResult/PDFResult.tsx, webstack/libs/frontend/src/lib/utils/strings.ts, webstack/libs/sagebase/src/lib/modules/auth/adapters/GoogleAdapter.ts, webstack/libs/sagebase/src/lib/modules/auth/adapters/GuestAdapter.ts, webstack/libs/sagebase/src/lib/modules/auth/adapters/SpectatorAdapter.ts, webstack/libs/shared/src/lib/types/server/serverconfig.ts, webstack/libs/shared/src/lib/utils/index.ts, webstack/libs/shared/src/lib/utils/strings.ts, webstack/sage3-dev.hjson, webstack/sage3-prod.hjson
```
// Webserver configuration
"webserver": {
"logLevel": "partial", // all | partial | none,
"uploadLimit": "5GB" // file upload size limit in string, optional units: KB, MB, GB, TB
},
```
=> [Backend]  add configuration for server log and server upload limit size

webstack/apps/webapp/src/app/pages/board/layers/background/BackgroundLayer.tsx, webstack/apps/webapp/src/app/pages/board/layers/ui/components/AppToolbar.tsx, webstack/apps/webapp/src/app/pages/board/layers/ui/components/Interactionbar.tsx, webstack/apps/webapp/src/app/pages/board/layers/ui/components/InteractionbarShortcuts.tsx, webstack/apps/webapp/src/app/pages/board/layers/ui/components/LassoToolbar.tsx, webstack/libs/applications/src/lib/apps/Stickie/Stickie.tsx
- Memoized Lasso and Whiteboard
- Swapped grab and pointer interaction positions
- Hamburger menu
=> [Controls] Tweaks to Interaction Bar & Leave App Button Positions

webstack/libs/frontend/src/lib/hooks/useFiles.tsx
Reverting changes from commit 86ca653.
This commit introduced file assets not being downloaded on the client and the client appearing out of sync.
Reverting this reintroduces the drag-drop of files not opening the app.
=> [REVERT] Revert changes from commit 86ca653

webstack/apps/webapp/src/app/pages/client/Client.tsx
UseEffect to check if client is electron....if so....redirect user properly and don't show the open client webpage.
=> [Client-Page] Client Page to open in desktop app shows in electron fix

webstack/apps/homebase/src/api/routers/custom/asset.ts, webstack/apps/webapp/src/app/pages/board/layers/background/components/Background.tsx, webstack/libs/frontend/src/lib/hooks/useFiles.tsx, webstack/libs/frontend/src/lib/stores/message.ts, webstack/libs/shared/src/lib/types/schemas/message.ts
https://github.com/user-attachments/assets/42c31612-efea-44a0-b5f9-4c85844a1719
=> [Backend] upload messages

webstack/apps/homebase/src/api/collections/assets.ts, webstack/apps/homebase/src/api/routers/custom/asset.ts, webstack/apps/homebase/src/main.ts, webstack/apps/homebase/src/web/http-server.ts, webstack/apps/webapp/src/app/pages/board/layers/background/components/Background.tsx, webstack/libs/frontend/src/lib/stores/asset.ts, webstack/libs/frontend/src/lib/stores/kernel.ts
- reload the asset store after someone else uploads a file
- set caching on asset and static files (nothing was cached by the browser)
- improve logs
=> [Assets] reload asset-store after upload 

webstack/libs/applications/src/lib/apps/Chat/Chat.tsx
Ai = Purple
Others = Gray
Yours = Blue  (Doesn't follow your user color now. Some people felt it was confusing, so following Apple iMessage format)
=> [Chat] Chat bubbles use same color as stickies for contrast

webstack/libs/applications/src/lib/apps.json, webstack/libs/applications/src/lib/apps.ts, webstack/libs/applications/src/lib/apps/AssetLink/AssetLink.tsx, webstack/libs/applications/src/lib/apps/AssetLink/components/AssetCard.tsx, webstack/libs/applications/src/lib/apps/AssetLink/index.ts, webstack/libs/applications/src/lib/apps/BoardLink/components/BoardCard.tsx, webstack/libs/applications/src/lib/apps/BoardLink/components/OtherServerCard.tsx, webstack/libs/applications/src/lib/apps/WebpageLink/WebpageLink.tsx, webstack/libs/applications/src/lib/initialValues.ts, webstack/libs/applications/src/lib/types.ts, webstack/libs/frontend/src/lib/hooks/useFiles.tsx, webstack/libs/frontend/src/lib/utils/setupAppForFiles.ts
=> [NEW] Adding basic support for unknown files

webstack/apps/webapp/src/app/pages/board/layers/ui/UILayer.tsx, webstack/apps/webapp/src/app/pages/board/layers/ui/components/AppToolbar.tsx, webstack/apps/webapp/src/app/pages/board/layers/ui/components/Interactionbar.tsx, webstack/apps/webapp/src/app/pages/board/layers/ui/components/LassoToolbar.tsx, webstack/apps/webapp/src/app/pages/board/layers/ui/components/Menus/BoardContextMenu.tsx, webstack/apps/webapp/src/app/pages/board/layers/ui/components/Menus/ContextButton.tsx, webstack/apps/webapp/src/app/pages/board/layers/ui/components/Menus/Menus/IntelligenceMenu.tsx, webstack/apps/webapp/src/app/pages/board/layers/ui/components/Menus/ToolbarButton.tsx, webstack/libs/applications/src/lib/ai-apps.ts, webstack/libs/applications/src/lib/apps.ts, webstack/libs/frontend/src/lib/ui/components/modals/Alfred.tsx, webstack/tools/generators/regen/index.ts
https://github.com/user-attachments/assets/1ccb2478-88cb-410f-9ea2-63d8ccd0c572
=> [Ai] Restrict Ai button on App Toolbar if app is not Ai Enabled

seer/app/image.py, seer/libs/utils.py, webstack/apps/webapp/src/app/pages/board/layers/background/components/DragAndDropBoard.tsx, webstack/apps/webapp/src/app/pages/board/layers/ui/components/AppToolbar.tsx, webstack/apps/webapp/src/app/pages/board/layers/ui/components/Interactionbar.tsx, webstack/apps/webapp/src/app/pages/board/layers/ui/components/Menus/BoardContextMenu.tsx, webstack/libs/frontend/src/lib/ui/components/modals/ConfirmModal.tsx
- Move the confirmation popup closer to user when deleting annotations
- Move Modal for deleting app
- Could be extended to other modals
=> Dev UI tweaks2

webstack/apps/webapp/src/app/pages/board/layers/ui/components/Menus/Menus/NavigationMenu.tsx, webstack/libs/frontend/src/lib/stores/app.ts
=> [Navigation Menu] Show all apps button added 

webstack/libs/applications/src/lib/apps/ImageViewer/ImageViewer.tsx
Image apps were invisible if the file was not found. If the URL is not set yet in the image viewer app, than the background is visible and a broken image link icon is shown.
=> [ImageViewer] Background image visible when image is not found

webstack/libs/applications/src/lib/apps/Notepad/Notepad.tsx, webstack/libs/applications/src/lib/apps/Notepad/styles.css
=> [Notepad] Notepad colors for darkmode

webstack/apps/webapp/src/app/pages/home/Home.tsx
Use's could join password protected room using this button:
=> Fix issue where user could bypass the password protection on a room

webstack/apps/webapp/src/app/pages/board/layers/ui/components/MainButton.tsx
=> [UI] Icon on main menu button to indicate wall or client

webstack/apps/webapp/src/app/app.tsx, webstack/apps/webapp/src/app/pages/board/layers/ui/components/MainButton.tsx, webstack/apps/webapp/src/app/pages/board/layers/ui/components/Menus/Menus/ApplicationsMenu.tsx, webstack/apps/webapp/src/app/pages/board/layers/ui/components/Menus/Menus/Asset/AssetsPanel.tsx, webstack/apps/webapp/src/app/pages/board/layers/ui/components/Menus/Menus/Asset/Files.tsx, webstack/apps/webapp/src/app/pages/board/layers/ui/components/Menus/Menus/PluginsMenu.tsx, webstack/apps/webapp/src/app/pages/board/layers/ui/components/Menus/Menus/ScreenshareMenu.tsx, webstack/apps/webapp/src/app/pages/board/layers/ui/components/Menus/Menus/UsersMenu.tsx, webstack/apps/webapp/src/app/pages/board/layers/ui/components/Menus/ToolbarButton.tsx, webstack/apps/webapp/src/app/pages/home/Home.tsx, webstack/apps/webapp/src/app/pages/home/components/AssetList.tsx, webstack/apps/webapp/src/app/pages/home/components/MembersList.tsx, webstack/apps/webapp/src/app/pages/home/components/PluginsList.tsx, webstack/apps/webapp/src/index.html
- fix: viewport settings to make the content visible on ios
=> [IOS] Minimum work to make it usable

webstack/libs/applications/src/lib/apps/CSVViewer/CSVViewer.tsx
=> [CSV] center data in cells and align headers to bottom

seer/app/image.py, webstack/libs/applications/src/lib/apps/Chat/Chat.tsx
- show plain english text for actions
=> [AI] ai results

webstack/package.json, webstack/yarn.lock
=> [FIX] downgrading to canvas v2, because issues with v3

webstack/apps/webapp/src/app/pages/board/layers/ui/components/AppToolbar.tsx, webstack/apps/webapp/src/app/pages/board/layers/ui/components/Interactionbar.tsx, webstack/apps/webapp/src/app/pages/board/layers/ui/components/LassoToolbar.tsx, webstack/apps/webapp/src/app/pages/board/layers/ui/components/TagsDisplay.tsx, webstack/libs/frontend/src/lib/ui/components/modals/ConfirmModal.tsx
- first step for fixing #1129 
-
=> [UI] trying to limit ConfirmModal redraw

webstack/libs/applications/src/lib/apps/WebpageLink/WebpageLink.tsx
https://github.com/user-attachments/assets/6d66ce98-ef1c-41c6-baca-c5e01f8cf760
The embedded link seems to trigger a persistent refresh behavior.  This also occurs with single user on the board and is not dependent on other applications.  The behavior will persist as long as one user is in the board, even if they leave and return.
Use effect depends on s.meta?.title (string) instead of s.meta (object)
=> [APP] Fixed Embedded Links Recursive Refresh

webstack/apps/webapp/src/app/app.tsx, webstack/apps/webapp/src/app/pages/client/Client.tsx, webstack/libs/frontend/src/lib/stores/board.ts, webstack/libs/frontend/src/lib/stores/room.ts
Auto Join the room's membership when you enter a board with a shared board link.
=> [Board Link] Auto join room when using a shared board link

deployment/docker-compose-amd64.yml, deployment/docker-compose-arm64.yml, webstack/apps/homebase-yjs/src/main.ts, webstack/apps/homebase/src/main.ts, webstack/apps/webapp/proxy.conf.json
Moved WebRTC code from the main home base server to the homebase-yjs server.
=> [WebRTC] Move code from homebase to homebase-yjs

foresight/foresight/smartbits/sagecell.py, webstack/libs/applications/src/lib/apps/SageCell/SageCell.tsx, webstack/libs/applications/src/lib/apps/SageCell/components/statusbar.tsx, webstack/libs/applications/src/lib/apps/SageCell/components/toolbar.tsx, webstack/libs/applications/src/lib/apps/SageCell/index.ts, webstack/libs/applications/src/lib/components/AppWindow/AppWindow.tsx, webstack/libs/applications/src/lib/components/AppWindow/components/WindowBorder.tsx
https://github.com/user-attachments/assets/149b21cf-8766-4ec6-8e7b-173da4a1fd99
=> [Cell] working out the evaluation order for sagecells

webstack/libs/applications/src/lib/apps/TwilioScreenshare/TwilioScreenshare.tsx, webstack/libs/frontend/src/lib/stores/twilio.ts, webstack/sage3-dev.hjson
To decrease the amount of latency or stuttering video Jason experienced.
Limits:
```
Max Width: 1920
Max Height: 1920
Max FPS : 20
```
=> [Twilio] Resolution and FPS Limit

webstack/apps/webapp/src/app/pages/board/layers/background/components/Background.tsx, webstack/apps/webapp/src/app/pages/board/layers/ui/components/Menus/Menus/Asset/AssetsPanel.tsx, webstack/apps/webapp/src/app/pages/home/Home.tsx, webstack/libs/frontend/src/lib/hooks/useFiles.tsx, webstack/libs/frontend/src/lib/stores/asset.ts
Query Assets by roomId in the AssetStore
`const res = await APIHttp.QUERY<Asset>('/assets', { room: roomId });`
and subscribe by room
```
// Socket Subscribe Message
const route = '/assets?room=' + roomId;
// Socket Listenting to updates from server about the current assets
assetSub = await SocketAPI.subscribe<Asset>(route, (message) => {
```
=> [Assets] Asset store now queries subscriptions and update

webstack/apps/webapp/src/app/pages/board/layers/background/components/Background.tsx, webstack/apps/webapp/src/app/pages/board/layers/ui/components/Menus/Menus/Asset/AssetsPanel.tsx, webstack/apps/webapp/src/app/pages/home/Home.tsx, webstack/libs/frontend/src/lib/hooks/useFiles.tsx, webstack/libs/frontend/src/lib/stores/asset.ts
=> Revert "[Assets] Asset store now queries subscriptions and update"

webstack/libs/frontend/src/lib/providers/useUserSettings.tsx
Not sure if it makes sense, but scales more ;-)
=> [UI] multiply by devicePixelRatio instead of divide?

webstack/libs/applications/src/lib/apps/SageCell/components/toolbar.tsx
=> [UI] a better ordering in 2D for cells

webstack/apps/webapp/src/app/pages/client/Client.tsx
=> [Join Board Toast] Toast Information

webstack/apps/webapp/src/app/pages/board/layers/ui/UILayer.tsx, webstack/apps/webapp/src/app/pages/board/layers/ui/components/Menus/BoardContextMenu.tsx
=> [UI] Context back button and Toolbar Center

webstack/apps/webapp/src/app/pages/board/layers/ui/components/LassoToolbar.tsx
- Changed grouped (lassoed) app toolbar's bottom offset 6px to 50px
- Auto-lint
https://github.com/SAGE-3/next/pull/1182
=> [FIX] Intersection of Grouped App Toolbar and UI Navbar

webstack/apps/webapp/src/app/pages/board/layers/ui/UILayer.tsx, webstack/libs/frontend/src/lib/hooks/useRouteNav.tsx
Navigates similar to a browser. Does not keep history between client restarts or server change.
=> [UI Board] Back and Forward button to navigate quickly between boards

webstack/apps/webapp/src/app/pages/board/layers/background/components/Apps.tsx
- 'c' command test if there's a selection and copy the selection
- otherwise works as before
- clears the clipboard if not app found
- Using batch create.
- addresses #1185
https://github.com/user-attachments/assets/546fbe96-b3e5-4366-b7e4-2a3dd3eb43d5
=> [UI] Copy/paste also works for app selection

webstack/libs/frontend/src/lib/ui/components/party/Party.tsx, webstack/libs/frontend/src/lib/ui/components/party/components/PartyInstance.tsx, webstack/libs/frontend/src/lib/ui/components/party/components/PartyStore.ts
=> [Party] Chat pollution and FPS drop

deployment/configurations/fluentd/conf/fluent-dev.conf, deployment/configurations/fluentd/conf/fluent-prod.conf, deployment/configurations/fluentd/conf/fluent.conf, deployment/configurations/fluentd/log/.gitignore, seer/app/chat.py, seer/app/code.py, seer/app/image.py, seer/app/web.py, seer/libs/ai_logging.py, seer/main.py, seer/requirements.txt, webstack/apps/homebase/src/api/routers/custom/config.ts, webstack/libs/applications/src/lib/apps/Chat/tRPC.ts, webstack/libs/shared/src/lib/types/server/serverconfig.ts
- Adding fluent to track prompts
=> [Dev] azure ai

webstack/libs/applications/src/lib/apps/Stickie/Stickie.tsx
=> [Stickies] Lightened the background color of stickies

webstack/apps/webapp/src/app/pages/home/Home.tsx, webstack/libs/frontend/src/lib/ui/components/modals/CreateBoardModal.tsx, webstack/libs/frontend/src/lib/ui/components/modals/CreateRoomModal.tsx, webstack/libs/frontend/src/lib/ui/components/modals/EditBoardModal.tsx, webstack/libs/frontend/src/lib/ui/components/modals/EditRoomModal.tsx, webstack/libs/shared/src/lib/utils/is-alphanumeric.ts
=> Room and board names

webstack/apps/webapp/src/app/pages/board/layers/ui/components/AppToolbar.tsx, webstack/libs/applications/src/lib/apps/PDFViewer/PDFViewer.tsx, webstack/libs/applications/src/lib/apps/PDFViewer/index.ts
=> PDF Fixes and pdf toolbar consistent icon sizes.

webstack/apps/webapp/src/app/pages/board/layers/ui/components/Menus/Menus/KernelsMenu.tsx, webstack/libs/applications/src/lib/apps/CodeEditor/CodeEditor.tsx, webstack/libs/applications/src/lib/apps/SageCell/SageCell.tsx, webstack/libs/applications/src/lib/apps/SageCell/components/statusbar.tsx, webstack/libs/applications/src/lib/apps/SageCell/components/toolbar.tsx, webstack/libs/frontend/src/lib/ui/components/modals/CreateKernelModal.tsx
=> [SAGECell] More kernel types

webstack/libs/applications/src/lib/apps/Clock/Clock.tsx, webstack/libs/applications/src/lib/apps/Clock/index.ts, webstack/libs/applications/src/lib/apps/Stickie/Stickie.tsx
- Added feature that allows the color of the clock digits to be changed
- Altered initialization color of digits slightly to better match with the SageColor color pallete
=> [UI] Clock Digit Color Picker

webstack/apps/webapp/src/app/pages/board/layers/ui/UILayer.tsx, webstack/apps/webapp/src/app/pages/board/layers/ui/components/BoardTitle.tsx, webstack/libs/frontend/src/lib/ui/components/general/Clock.tsx
- Addresses #1266 
- dark and light
=> fix: add bg to clock and room name on top

webstack/apps/webapp/src/app/pages/board/layers/background/components/DragAndDropBoard.tsx, webstack/apps/webapp/src/app/pages/board/layers/ui/components/Menus/Menus/ApplicationsMenu.tsx, webstack/libs/applications/src/lib/apps/Timer/Timer.tsx, webstack/libs/frontend/src/lib/ui/components/modals/Alfred.tsx
=> [APP] make timer scalable

webstack/libs/frontend/src/lib/hooks/useFiles.tsx, webstack/package.json, webstack/yarn.lock
=> [Frontend] load session fix
