SAGE-3/next

webstack/apps/webapp/src/app/pages/board/Board.tsx
webstack/libs/frontend/src/lib/utils/urlBoardCheck.tsx

To avoid cross server effects added "hostname" to the local storage key for board routing.

[Board Route] Added hostname to local storage key.

---

webstack/clients/electron/electron.js
webstack/clients/electron/package.json
webstack/clients/electron/yarn.lock
webstack/libs/applications/src/lib/apps/Stickie/Stickie.tsx

- it blocks ctrl/apple + click to create new webviews.
- For now, drag a link from webview to board to create new webviews.

[Client] Update to electron 25

---

webstack/clients/electron/electron.js
webstack/clients/electron/package.json
webstack/clients/electron/preload.js
webstack/clients/electron/yarn.lock
webstack/libs/applications/src/lib/apps/Webview/Webview.tsx

- like in a browser, when CMD/CTRL click a link in a webview, open a new webview
- feature was disabled a while back because API changed in electron
- Back, using communication between render and main processes in Electron

[Webview] open links with CMD-click

---

webstack/apps/homebase/src/api/routers/custom/presencethrottle.ts
webstack/apps/homebase/src/api/routers/custom/subscription.ts
webstack/libs/backend/src/lib/utils/presence.ts
webstack/libs/frontend/src/lib/hooks/useUser.tsx
webstack/libs/frontend/src/lib/stores/presence.ts

Situation where user is signed in from multiple locations:
- Cursor and Viewport should update with whatever the last update it received, no matter the sign in location
- When the user signed out of one location the other location's presence got blocked and would require a hard client refresh to fix
- User updates (color, client type, name) were not being populated to other sign in location. Fix with a subscription to your own User Doc incase you change from another location.
Memory leak fix in PresenceThrottle

[Presence] Various Fixes

---

deployment/docker-compose-amd64.yml
deployment/docker-compose-arm64.yml
deployment/docker-compose-backend.yml

- switch the fastapi docker images to sagekernelserver repo on github
- arch specific in production
- dev pulls the multi-arch image we can build on laptops

[Backend] fastapi images

---

webstack/apps/webapp/src/app/pages/board/layers/ui/components/Panels/Controller/Controller.tsx

Since a lot of confusion:
- regular click : back to room
- shift-click : back to previous page (i.e. board when using a board link)

[UI] switch the operation of the 'back' button

---

webstack/apps/homebase/src/api/collections/index.ts
webstack/apps/webapp/src/app/pages/home/Home.tsx
webstack/libs/frontend/src/lib/config/urls.ts
webstack/libs/frontend/src/lib/ui/components/general/MainButton.tsx
webstack/libs/frontend/src/lib/ui/components/modals/CreateBoardModal.tsx
webstack/libs/frontend/src/lib/ui/components/modals/EnterBoardByURLModal.tsx
webstack/libs/shared/src/lib/types/schemas/board.ts
webstack/libs/shared/src/lib/utils/gen-id.ts
webstack/package.json
webstack/yarn.lock

- Generate a code when creating a board (XXXXX-XXXXX), more memorable than URL
- Fixing the data model when display a board
- Accepting code when entering a board, like the long URL
https://github.com/SAGE-3/next/assets/5595452/e6ea6f7b-5b6d-4a7e-aa95-aecdc18a4f07

[UI] Using a code to enter board, like Zoom

---

webstack/libs/applications/src/lib/apps/Stickie/Stickie.tsx

#870 
Uses `onFocus` and `onBlur`. 
When a user `focuses` on a stickie TEXTAREA they enter a local "EDIT" mode which ignores new updates from other users.
When the user `de-focuses` the stickie's TEXTAREA they send the new updated text to the server and exits the "EDIT" mode.
https://github.com/SAGE-3/next/assets/19752298/2b5b18d0-b0bc-4e61-836b-a365b604574c

[Stickies] Different way of managing stickie state

---

webstack/apps/homebase/src/main.ts
webstack/libs/applications/src/lib/apps/CodeEditor/CodeEditor.tsx
webstack/libs/applications/src/lib/apps/SageCell/SageCell.tsx
webstack/libs/applications/src/lib/apps/Stickie/Stickie.tsx

The initial state for Yjs will be lost if multiple people are on the board, due to us only syncing with database when only one user on board.
Fix looks like this: 
```typescript
const users = provider.awareness.getStates();
const count = users.size;
// Sync current ydoc with that is saved in the database
const syncStateWithDatabase = () => {
// Clear any existing lines
yText.delete(0, yText.length);
// Set the lines from the database
yText.insert(0, s.text);
};
// If I am the only one here according to Yjs, then sync with database
if (count == 1) {
syncStateWithDatabase();
} else if (count > 1 && props._createdBy === user?._id) {
// There are other users here and I created this app.
// Is this app less than 5 seconds old...this feels hacky
const now = await serverTime();
const created = …
```

[Yjs Apps] Initial state being lost with multiple users on board

---

webstack/libs/applications/src/lib/components/AppWindow/AppWindow.tsx

Attempt at optimization when the app is outside the user's viewport
Uses CSS `content-visibility` setting. `hidden` and `visible`

[Optimization] App window render culling the app outside user's viewport

---

webstack/libs/shared/src/lib/utils/fuzzy-search.ts
webstack/package.json
webstack/yarn.lock

- Corrected current regex search implementation to use Fuse.JS's fuzzy search; now allowing for symbols
- Added Fuse.JS Library 
- [https://www.fusejs.io/](https://www.fusejs.io/)
- [https://www.npmjs.com/package/fuse.js?activeTab=readme](https://www.npmjs.com/package/fuse.js?activeTab=readme)

Corrections to Fuzzy Search Implementation

---

webstack/apps/webapp/src/app/pages/board/layers/ui/components/Panels/Panel.tsx

- restored touch onClick functionality, bug was due to ```preventdefault()``` being called prior to knowing if the user has longPressed.
- ```preventdefault()``` now only triggers after longPress's ```callback(event)``` triggers
The usage of longPress in this instance may cause additional bugs. 
- Regarding the Back button in the Controller (top panel); there are rare observed instances where the popup does not release the mouse down and can causes propagation to the onClick function.
- Non-popup long press does not prevent propagation to onClick
- **_Proposed alternative solution_** provided in line 92-93 is to use onContextMenu instead.  This allows for right clicking with mouse and long press with touch.

Restored onClick functionality to board controller panel for touch users

---

webstack/apps/webapp/src/app/pages/board/layers/background/components/Presence/PresenceComponent.tsx
webstack/apps/webapp/src/app/pages/board/layers/background/components/Presence/Viewports.tsx
webstack/apps/webapp/src/app/pages/board/layers/ui/components/PresenceFollow.tsx
webstack/libs/shared/src/lib/types/schemas/presence.ts

One way to fix the bounce when zooming as a wall due to the logic from #826 
`PresenceSchema` now has the property `selfUpdate: boolean`

[Viewport] Bounce when zooming when wall

---

webstack/apps/webapp/src/app/pages/board/layers/background/BackgroundLayer.tsx
webstack/apps/webapp/src/app/pages/board/layers/background/components/Background.tsx
webstack/apps/webapp/src/app/pages/board/layers/background/components/Lasso.tsx
webstack/apps/webapp/src/app/pages/board/layers/background/components/Whiteboard/Whiteboard.tsx
webstack/apps/webapp/src/app/pages/board/layers/ui/components/BoardContextMenu.tsx
webstack/apps/webapp/src/app/pages/board/layers/ui/components/Interactionbar.tsx
webstack/apps/webapp/src/app/pages/board/layers/ui/components/InteractionbarShortcuts.tsx
webstack/apps/webapp/src/app/pages/board/layers/ui/components/Panels/Annotations/AnnotationsPanel.tsx
webstack/libs/applications/src/lib/components/AppWindow/AppWindow.tsx
webstack/libs/frontend/src/lib/ui/components/context-menu/context-menu.tsx
webstack/libs/frontend/src/lib/ui/components/context-menu/style.scss
webstack/libs/frontend/src/lib/ui/theme/theme.ts

- Updated context menu look
- Opaque dark mode interaction bar inactive colors
- ideally this colorscheme logic would be in `theme.ts` however, unintended css changes may occur.  Therefore color logic is relegated to interaction bar component  (for now)
- Tooltips in context menu now show above context menu.  (context menu z-index reduced to approximately tooltip's zindex - 1)
- Removed movement behaviors associated with space bar
- Removed irrelevant tips involving old movement scheme that was in annotations panel
- Apps deselect when touchpad panning, mouse drag, or touchscreen (onDown) is initially clicked on the board's background
- When switching to pen or eraser it will clear the selectedApp and selectedAppIds
- Lasso
- Shift + Selection will now deselect prior selected apps
- Ctrl …

[Controls] Incremental Clean-up and Minor Improvements

---

webstack/clients/electron/electron.js

Another check in the electron client to detect the gray screen.
If the page.title == 'Error' then redirect to the landing page.

[Electron] Gray Screen 'Cannot GET /'

---

webstack/apps/webapp/src/app/pages/home/components/BoardPreview.tsx

To increase performance on homepage the board previews now cache the apps instead of fetching every component re-render. Cache has an expiration of 60 seconds.

[Homepage + Performance] Boardpreview cache of apps

---

webstack/libs/frontend/src/lib/stores/twilio.ts
webstack/sage3-dev.hjson

Noticed during meeting starting a screenshare on Ryan's computer would have RJ's phone start FaceTime.
The Twilio Store connect function's video property was the culprit. Providing this property triggers the user to start webcam sharing. Removed property

[Twilio] Hotfix to remove video property to Twilio connect()

---

webstack/apps/webapp/src/app/pages/board/layers/background/components/Apps.tsx

ctrl+d cmd+d shortcut:
- doesn't delete pinned apps
- single app or in a group selection

[UI] delete shortcut doesn't delete pinned app

---

webstack/apps/homebase/src/api/collections/index.ts
webstack/apps/homebase/src/api/routers/custom/config.ts
webstack/apps/homebase/src/main.ts
webstack/apps/webapp/src/app/pages/home/Home.tsx
webstack/libs/backend/src/lib/utils/presence.ts
webstack/libs/frontend/src/lib/stores/presence.ts

Presence had some state in the node server. With the new node_server replicas, this can cause some issues. This moves the state to the REDIS database to ensure the state is synced across clients.
Users can connect multiple times so for each socket connected there is a stored value in the REDIS database `${SOCKET_ID}:${USER_ID}` with a TTL over 30 secs that is refreshed every 15secs. 
Every 30 secs the backend checks the presence collection for users `ONLINE` and verifies by ensuring the path has at least one matching pair for the USER_ID.
#1155

[Presence] Node Server Replicas Presence issues

---

webstack/tools/generators/newapp/index.ts

Added missing export ```output += `export * from './ai-apps';\n`;``` to ```tools/generators/newapp/index.ts``` to fix compilation error.
1) Tested by starting development services (yarn start, etc.)
2) Created in a new app with ```cd next/webstack && yarn newapp``` 
3) Restarted the development services.
4) No errors shown

[TOOLS] New App Creation Fix

---

webstack/libs/frontend/src/lib/providers/useCursorBoardPosition.tsx

https://github.com/user-attachments/assets/fac274a3-7d95-4270-9f52-d87f4b52121d
Video demonstrates a fault in the optimization when a user uses left click and drag, then the user stops moving while still holding left click.  Thereafter, the user resumes dragging.  We clearly see that the SageCell rerender is triggered and the frame rate drops.
- Added a variable to store the relevant mouse down state.  So when ```throttleMoveRef``` triggers the ```useEffect``` it wont re-enable to ```eventListener```.
- For unknown reason(s), middle mouse drag was ignored.  I enabled middle mouse drag to receive this optimization as well.  Hopefully that won't cause any issues...
- Cleaned up commented out code as well.
- No regression testing done, just ensured that the relevant benefits of the fix were …

[PERFORMANCE] Fixed Drag Optimization Breaking

---

webstack/apps/webapp/src/app/pages/board/layers/background/BackgroundLayer.tsx

Hopefully this will address the following issue: https://github.com/SAGE-3/next/issues/1100
Since the view port always seems to be either centered on apps or in the top left corner; one plausible cause is that the default:
```typescript
const [localBoardPosition, setLocalBoardPosition] = useState({ x: 0, y: 0, scale: 0 });
```
which should update via this useEffect:
```typescript
// Forward boardPosition to localBoardPosition
useEffect(() => {
setLocalBoardPosition({ x: boardPosition.x, y: boardPosition.y, scale: scale });
}, [boardPosition.x, boardPosition.y, scale]);
```
is inhibited by some race condition or weird interaction maybe preventing that periodically.   Setting the default to the UIStore states may resolve the issue.
Merge and pray that the issue never appears again.
PS: …

[Board] Setting the Default Board Position to the UiStore's State

---

webstack/apps/webapp/src/app/pages/board/layers/ui/components/AppToolbar.tsx

App toolbar intersecting with UI navigation bar
Increase height of app bar default position by 50px

[FIX] Intersection of App Toolbar and UI Navbar

---

webstack/libs/applications/src/lib/apps/MapGL/MapGL.tsx

MapGL would crash and show a red screen in the app window on re-entering a board with a mapgl app open.

[MapGl] Crash due to geotiff removal

---

webstack/apps/webapp/src/app/pages/board/layers/ui/UILayer.tsx
webstack/apps/webapp/src/app/pages/board/layers/ui/components/AppToolbar.tsx
webstack/apps/webapp/src/app/pages/board/layers/ui/components/EscapeApp.tsx
webstack/apps/webapp/src/app/pages/board/layers/ui/components/index.ts

It has been noted, during internal lab meetings, that the preexisting methods of deselecting an app that has captured all user inputs is not user friendly.
Existing methods:
- App toolbar -> Hamburger -> Deselect Application
- Selecting another interaction mode
The `EscapeApp.tsx` code checks each app on the board to see if it is within the user's viewport and if it selected.  If the user's viewport is smaller than the app and is inside the app and the app is selected, then we show the escape app button in the UI bar at the bottom of the screen.
The `EscapeApp.tsx` code only does it checks if the app is selected and will break on first valid hit to mitigate performance degradation by introducing this feature.
https://github.com/user-attachments/assets/582babb7-db29-4e62-a939-9c46ac4b0b21 …

[Feature] Another Method to Deselect App When Zoomed In Too Close

---

webstack/apps/homebase/src/api/collections/apps.ts
webstack/apps/webapp/src/app/pages/home/components/BoardPreview.tsx
webstack/libs/frontend/src/lib/config/urls.ts

Board Preview on the homepage previously fetched the whole App object and built the preview locally. 
Moved logic to server to decompose app preview to just a subset of the data:
```
{ 
position: Position; 
size: Size; 
type: AppName; 
id: string 
}
```
Should hopefully help Home page performance.

[BoardPreview] Only a subset of the Apps array

---

seer/requirements.txt
webstack/libs/applications/src/lib/apps/Chat/Chat.tsx
webstack/libs/applications/src/lib/components/AppWindow/AppWindow.tsx

- resize app in board space with fit in viewport space
- same logic as window manager on macOS
- double-click an edge to extend the app in that direction,
- double-click a corner also extend the app
- with ALT key in also extends the opposite side.

[UI] resize app with border/corner double-click
